[general]
working_directory = "~"
[window]
dimensions = { columns = 100, lines = 30 }
opacity = 0.9
padding = { x = 10, y = 10 }
decorations = "Full"  # Options: "Full", "None", "Transparent", "Buttonless"
dynamic_title = true
decorations_theme_variant = "None"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 20.0

[colors]
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }
normal = { black = "#282c34", red = "#e06c75", green = "#98c379", yellow = "#e5c07b", blue = "#61afef", magenta = "#c678dd", cyan = "#56b6c2", white = "#dcdfe4" }

[cursor]
style = { shape = "Block", blinking = "Always" }


[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },          
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" }
]

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0
